export const aiChatStatusCopy = {
  metadataTitle: "AI Chat 상태 진단",
  title: "AI Chat 상태 진단",
  description:
    "Vercel Server에서 AI Gateway Stage로 직접 연결되는지 확인합니다. 브라우저는 프록시로 사용하지 않습니다.",
  configTitle: "실행 설정",
  probeTitle: "기본 요청",
  resultTitle: "응답 결과",
  eyebrow: "Vercel Server Probe",
  fixedRequestLabel: "고정 테스트 요청",
  action: "기본 요청 테스트",
  loading: "요청 중",
  retryAfter: (seconds: number) => `${seconds}초 후 재시도`,
  status: {
    enabled: "활성화됨",
    disabled: "비활성화됨",
    configured: "설정됨",
    missing: "미설정",
    success: "성공",
    failure: "실패",
    idle: "아직 요청하지 않았습니다.",
  },
  labels: {
    environment: "환경",
    enabled: "AI Chat Enabled",
    keyConfigured: "API Key",
    baseUrl: "Base URL",
    model: "Model",
    upstreamStatus: "Upstream HTTP status",
    elapsed: "Elapsed",
    finishReason: "Finish reason",
    responseType: "Response type",
    responseServer: "Response server",
    checkedAt: "Checked at",
    result: "Result",
    finalAnswer: "Final answer",
  },
  values: {
    other: "Other",
  },
  notices: {
    disabled: "AI Chat이 비활성화되어 있어 진단 요청을 실행하지 않습니다.",
    missingKey: "AI_CHAT_API_KEY가 설정되지 않았습니다.",
    productionDisabled: "Production 환경은 AI Chat Enabled=false 설정을 유지하므로 probe를 실행하지 않습니다.",
    rateLimit:
      "서버 인스턴스별 호출 제한은 분당 2회, 동시 실행 1회입니다. Retry-After 이후 다시 시도해 주세요.",
  },
  errors: {
    rateLimited: "호출 횟수 제한에 걸렸습니다.",
    albForbidden:
      "Gateway 앞단(ALB/WAF)에서 접근이 거부되었습니다. 구체적인 차단 규칙은 이 화면만으로 확인할 수 없습니다.",
    disabled: "서버에서 AI Chat이 비활성화되어 있다고 응답했습니다.",
    notConfigured: "서버에서 AI_CHAT_API_KEY가 없다고 응답했습니다.",
    invalidResponse: "Gateway 응답 형식이 예상과 다릅니다.",
    timeout: "Gateway 요청 시간이 초과되었습니다.",
    network: "Gateway 또는 Vercel Server 네트워크 연결에 실패했습니다.",
    generic: "진단 요청을 완료하지 못했습니다.",
  },
} as const;
